- name: Blue/Green Deployment
  hosts: client_servers
  tasks:
    - name: Deploy 'Green' Version
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-green
            namespace: my-namespace
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: myapp
                version: green
            template:
              metadata:
                labels:
                  app: myapp
                  version: green
              spec:
                containers:
                  - name: myapp-container
                    image: "myapp:{{ new_version }}"
                    ports:
                      - containerPort: 8080

    - name: Update Service to 'Green' Version
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: myapp-service
            namespace: my-namespace
          spec:
            selector:
              app: myapp
              version: green
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8080
