- name: Rollback to Previous Working Deployment
  hosts: client_servers
  tasks:
    - name: Scale down the broken deployment
      kubernetes.core.k8s.k8s_scale:
        api_version: apps/v1
        kind: Deployment
        name: myapp-deployment
        namespace: my-namespace
        replicas: 0

    - name: Deploy working stable version
      kubernetes.core.k8s.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: app-deployment
            namespace: my-namespace
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: app
            template:
              metadata:
                labels:
                  app: app
              spec:
                containers:
                  - name: app-container
                    image: "app:working-version"
                    ports:
                      - containerPort: 80
