apiVersion: v1
kind: ConfigMap
metadata:
  name: semarchy-config
  namespace: {{ .Values.namespace }}
data:
  XDM_REPOSITORY_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
  XDM_REPOSITORY_USERNAME: xdm_db_administrator@sql-xdm-test-dev-uc1
  XDM_REPOSITORY_READONLY_USERNAME: xdm_db_administrator_ro@sql-xdm-test-dev-uc1
  XDM_REPOSITORY_URL: jdbc:sqlserver://sql-xdm-test-dev-uc1.database.windows.net:1433;databaseName=semarchy_repository
  db_cluster_username: gadataadmin