- hosts: ubuntu
  become: true
               
  tasks:
  - name: Uninstall Net-Tools
    apt: 
      name: net-tools
      state: absent

  - name: Uninstall NMAP
    apt:
      name: nmap
      state: absent

  - name: Uninstall HTOP
    apt:
      name: htop
      state: absent