---
- hosts: all
  become: true
  tasks:
    - name: Stop falcon-sensor systemctl service
      systemd:
        name: falcon-sensor 
        state: stopped

    - name: Stop falcon-sensor service
      service:
        name: falcon-sensor 
        state: stopped

    - name: Uninstall Crowdstrike Agent
      apt:
        name: falcon-sensor
        state: absent

    - name: Remove copied Crowdstrike installation package
      file:
        path: /tmp/falcon-sensor_7.02.0-15705_amd64.deb
        state: absent
