- hosts: all
  become: true
  tasks:
    - name: Copy Qualys
      copy:
        src: ~/ansible/packages/qualys/QualysCloudAgent.deb
        dest: /tmp/QualysCloudAgent.deb
        owner: root
        group: root
        mode: "0644"

    - name: Install Qualys Agent
      apt:
        deb: /tmp/QualysCloudAgent.deb
        state: present
