- hosts: all
  become: true
  vars_files: ~/ansible/vaults/splunk-vault.yml
  vars:
    splunkadmin: "SplunkAdmin"

  tasks:
    - name: Validate Splunk is Installed
      stat:
        path: /opt/splunk
      register: splunk_is_installed
  
    - name: Copy Splunk
      copy:
        src: ~/ansible/packages/splunk/splunk-9.1.1-heavy-forwarder-linux-2.6-amd64.deb
        dest: /tmp/splunk-9.1.1-heavy-forwarder-linux-2.6-amd64.deb
        owner: root
        group: root
        mode: '0644'
      when: not splunk_is_installed.stat.exists

    - name: Copy Splunk Certificate
      copy:
        src: ~/ansible/packages/splunk/splunkclouduf.spl
        dest: /tmp/splunkclouduf.spl
        owner: root
        group: root
        mode: '0644'
      when: not splunk_is_installed.stat.exists      

    - name: Install Splunk Agent
      apt:
        deb: /tmp/splunk-9.1.1-heavy-forwarder-linux-2.6-amd64.deb
        state: present
      when: not splunk_is_installed.stat.exists  

    - name: Allow port 9997 through UFW
      ufw:
        rule: allow
        port: '9997'
        proto: tcp
      when: not splunk_is_installed.stat.exists    

    - name: Install the Splunk Heavy Forwarder
      command:
        cmd: /opt/splunk/bin/splunk install app /tmp/splunkclouduf.spl
        creates: /opt/splunk
      when: not splunk_is_installed.stat.exists

    - name: Create User-Seed Config File
      copy:
        dest: "/opt/splunk/etc/system/local/user-seed.conf"
        content: |
          [user_info]
          USERNAME = {{ splunkadmin }}
          PASSWORD = {{ splunkpassword }}
      when: not splunk_is_installed.stat.exists         

    - name: Start the Splunk Heacvy forwarder
      command:
        cmd: /opt/splunk/bin/splunk start --accept-license --no-prompt --seed-passwd
      when: not splunk_is_installed.stat.exists 

    - name: Restart the Splunk Heavy forwarder
      command:
        cmd: /opt/splunk/bin/splunk restart
      when: not splunk_is_installed.stat.exists      
