apiVersion: apps/v1
kind: Deployment
metadata:
  name: -appserver-passive
  labels:
    app: -appserver-passive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: -appserver-passive
  template:
    metadata:
      labels:
        app: -appserver-passive
    spec:
      containers:
        - image: /myapp:5.3.19-passive
          name: -appserver-passive
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "5Gi"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: -config
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: _SETUP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: setup-token
                  key: -setup-token
            - name: myapp_REPOSITORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repo-password
                  key: myapp-repo-password
            - name: myapp_REPOSITORY_READONLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repo-ro-password
                  key: myapp-repo-ro-password
      restartPolicy: Always
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "-azure-secret-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: -appserver-passive
  labels:
    app: -appserver-passive
spec:
  ports:
    - port: 8080
  selector:
    app: -appserver-passive
