plugin: azure_rm

include_vm_resource_groups:
  - "*"

auth_source: msi

subscription_id: #Enter you Subscription ID

conditional_groups:
  linux_servers: "'linux' in os_profile.system"

exclude_host_filters:
  - os_profile.system == 'windows'
