question_data = [{"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "Toronto is the capital city of the North American country of Canada.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                  "question": "The color of the pills in the Matrix were Blue and Yellow.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
                  "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Pluto is a planet.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Celebrities",
                  "question": "Lady Gaga&#039;s real name is Stefani Joanne Angelina Germanotta.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "Unturned originally started as a Roblox game.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                  "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The Sonoran Desert is located in eastern Africa.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Comics",
                  "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "TF2: The Heavy&#039;s voice actor, Gary Schwartz, voices the Demoman as well ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Vehicles",
                  "question": "The term &quot;GTO&quot; was originated by Ferrari?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "Vietnam is the only country in the world that starts with V. ",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}]
