---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: {{ .Values.secretProvider.provider }}
  secretObjects:                              
  - data:
    - key: {{ .Values.secrets.setupToken.key }}                     
      objectName: {{ .Values.secrets.setupToken.objectName }}  
    secretName: {{ .Values.secrets.setupToken.secretName }}                
    type: {{ .Values.secretProvider.secretType }}
  - data:
    - key: {{ .Values.secrets.repoPassword.key }}                         
      objectName: {{ .Values.secrets.repoPassword.objectName }}                
    secretName: {{ .Values.secrets.repoPassword.secretName }}                  
    type: {{ .Values.secretProvider.secretType }}
  - data:
    - key: {{ .Values.secrets.repoROPassword.key }}                         
      objectName: {{ .Values.secrets.repoROPassword.objectName }} 
    secretName: {{ .Values.secrets.repoROPassword.secretName }}                     
    type: {{ .Values.secretProvider.secretType }}       
  parameters:
    usePodIdentity: {{ .Values.secretProvider.usePodIdentity | quote }}
    useVMManagedIdentity: {{ .Values.secretProvider.useVMManagedIdentity | quote }}  
    userAssignedIdentityID: {{ .Values.secretProvider.userAssignedIdentityID | quote }}      
    keyvaultName: {{ .Values.secretProvider.keyvaultName }} 
    cloudName: {{ .Values.secretProvider.cloudName | quote }}                  
    objects:  |
      array:
        - |
          objectName: {{ .Values.secrets.setupToken.objectName }}
          objectType: {{ .Values.secretProvider.objectType }}
          objectVersion: {{ .Values.secretProvider.objectVersion }} 
        - |
          objectName: {{ .Values.secrets.repoPassword.objectName }}
          objectType: {{ .Values.secretProvider.objectType }}
          objectVersion: {{ .Values.secretProvider.objectVersion }} 
        - |
          objectName: {{ .Values.secrets.repoROPassword.objectName }}
          objectType: {{ .Values.secretProvider.objectType }}
          objectVersion: {{ .Values.secretProvider.objectVersion }}
    tenantId: {{ .Values.secretProvider.tenantId }}
