apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.active.name }}
  labels:
    app: {{ .Values.app.active.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.active.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.active.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.active.name }}
    spec:
      containers:
        - image: {{ .Values.app.active.image }}
          name: {{ .Values.app.active.name }}
          resources:
            requests:
              memory: {{ .Values.app.active.requestsMemory }}
            limits:
              memory: {{ .Values.app.active.limitsMemory }}
          ports:
            - containerPort: {{ .Values.app.active.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.active.configMapRef }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.app.active.mountPath }}
              readOnly: {{ .Values.app.active.readOnly }}
          env:
            - name: SEMARCHY_SETUP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.setupToken.name }}
                  key: {{ .Values.secrets.setupToken.key }}
            - name: XDM_REPOSITORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.repoPassword.name }}
                  key: {{ .Values.secrets.repoPassword.key }}
            - name: XDM_REPOSITORY_READONLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.repoROPassword.name }}
                  key: {{ .Values.secrets.repoROPassword.key }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.volume.name }}
          csi:
            driver: {{ .Values.volume.driver }}
            readOnly: {{ .Values.app.active.readOnly }}
            volumeAttributes:
              secretProviderClass: {{ .Values.volume.secretProviderClass }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.active.name }}
  labels:
    app: {{ .Values.app.active.name }}
  namespace: {{ .Values.namespace }}    
spec:
  ports:
    - port: {{ .Values.app.active.servicePort }}
  selector:
    app: {{ .Values.app.active.name }}