plugin: azure_rm

include_vm_resource_groups:
  - "*"

auth_source: msi

subscription_id: #Enter you subscriptionID

conditional_groups:
  pexip: "'linux' in os_profile.system and 'pex' in name"
  ise: "'linux' in os_profile.system and 'uc1d-ise' in name"
  airflow: "'linux' in os_profile.system and 'airflow' in name"
  xpress: "'linux' in os_profile.system and 'uc1d-xpress' in name"
  test: "'linux' in os_profile.system and 'fhlinux' in name"

exclude_host_filters:
  - os_profile.system == 'windows'
  - name == 'uc1d-fhlinuxvm1'
