#Node Selectors are used when you want to restrict a Node to a certain workload
#Need to label your node first.

#k label nodes <node-name> size=large
#Has restrictions if you want to place pod on either Large or Medium.

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor

  nodeSelector:
    size: Large

---

 #Node Affinity is used when you want to restrict a Node to multiple key-values 

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In 
            values:
            - Large
            - Medium
