apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding 
  #namespace: my-space - if you want to limit it to a specific namespace. 
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: developer  
  apiGroup: rbac.authorization.k8s.io