apiVersion: admissionregistration.k8s.io/v1
kind: ValidataingWebhookConfiguration
metadata:
  name: "pod-policy-example.com"
webhook:
- name: "pod-policy-example.com"
  clientConfig: 
    url: "https://external-server.example.com" #if this is a external webhook server (not in cluster)
    service:
      namespace: "webhook-ns"
      name: "webhook-service"
    caBundle: "sdfdsfsC...sdfd" #need to enter certificates for webhook server deployment
    rules: #this is what will trigger the webhook, ex: when a deployment/pod is created
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"