# Add setup token
CATALINA_OPTS="$CATALINA_OPTS -DSEMARCHY_SETUP_TOKEN=CheckMeOut123"

# Add logging configuration
CATALINA_OPTS="$CATALINA_OPTS -Dorg.ops4j.pax.logging.property.file=$CATALINA_BASE/conf/log4j2.semarchy.xml"

export CATALINA_OPTS

#export XDM_SECRETS_EXTERNAL_AZURESECRETS_TYPE="AZURE"
#export XDM_SECRETS_EXTERNAL_AZURESECRETS_VAULTURL="https://kv-semarchy-vm-dev-uc1.vault.azure.net/"
#export XDM_SECRETS_EXTERNAL_AZURESECRETS_CREDENTIALS_TENANTID="eb83984f-99ea-46bb-be92-cca88ced3b85"
#export XDM_SECRETS_EXTERNAL_AZURESECRETS_CREDENTIALS_CLIENTID="16a52dea-c185-4580-83f2-614aa9006b8a"
#export XDM_SECRETS_EXTERNAL_AZURESECRETS_CREDENTIALS_CLIENTSECRET="yMb8Q~mIiYILpHAPm3nv5OKe4YF_Fk2D85TRtc1j"